### ISSUE TITLE
$ in password does not work

### ISSUE THREAD

**Issue by lechiJb** [vavrecan/keeweb-local-server#1]
Hey,

first thanks for that useful keeweb-plugin!

At the moment I try to open a keepass-file, encryped with a passphrase including a "$"-sign (e.g. "test$"). Unfortunately this files are not encryptable.

I also tried to debug the code for my own, but each time, I added only a comment in file plugin.js, the page shows only an error-message. I guess, the signature is not valid any more...

Thank in advance for your help!

Greets,

Christian

**Comment by vavrecan** [comment]
Hello, 
you mean the password to access the database you stored inside of the server.php script?
you need to use keeweb plugin utility to regenerate signature if you want to modify the code.
Thank you!

**Comment by lechiJb** [comment]
Yes, I mean the password to access the database.

With original keeweb (without plugin) I am able to open my keepass-file (password includes a "$"), but by using the local-server plugin I am not able to open it.
If I create a password without a "$"-symbol, I can open the file in both cases...

Now I am able to sign the plugin by myself and I added some debugging information to find the reason for this error. But unfortunately i have some understanding-issues and cannot figure out, the reason for the issue. Can you give me some tips, where to search?

Greets,

Christian

**Comment by vavrecan** [comment]
when you put this to the configuration file of server.php , did you escaped $ with backslash?
 e.g. \$  ?
