### ISSUE TITLE
Can't work from a subdirectory

### ISSUE THREAD

**Issue by wolveix** [vavrecan/keeweb-local-server#2]
Due to plugins/local-server/plugin.js referencing the server.php file from the root folder, this plugin won't work if KeeWeb is hosted from a subdirectory. You can get around this by placing a duplicate of the server.php file into the root directory of the entire server, but that could introduce other problems. Unfortunately, only you can fix this as it's signed by you.

Great plugin though!

**Comment by Wolveix** [comment]
This issue has been addressed in a forked repository: https://github.com/Arcruy/keeweb-server-storage/commit/7ed9e88b2925d373a76ca820f305484bdbae8205
