### ISSUE TITLE
Problems with the plugin with docker container antelle/keeweb 1.15.7

### ISSUE THREAD

**Issue by strmar** [vavrecan/keeweb-local-server#8]
I read that with the latest version 1.15.7 of keeweb you can use the plugin again or it was adapted.
but I always get the error message that the signature of the resource is invalid, see screenshot, but I have adapted everything as described in the README 
The plugin doesn't need to be signed anymore, because this was already done to you, or am I getting something wrong?

![Bildschirmfoto 2020-10-20 um 12 54 21](https://user-images.githubusercontent.com/70019447/96589514-328f6080-12e5-11eb-9b4d-42e776ec5884.png)

The only thing i had to change was the plugin url, otherwise he won't find the plugin in general

config.json 

{
  "settings": {
    "canOpen": true,
    "canOpenDemo": false,
    "canOpenSettings": true,
    "canCreate": false,
    "canImportXml": false,
    "canRemoveLatest": true,

    "dropbox": false,
    "webdav": false,
    "gdrive": false,
    "onedrive": false,
    "localServerStorage": true
  },
  "plugins": [{
    "url": "plugins/plugins/local-server",
    "skipSignatureValidation": true
  }]
}
Thanks in advance for your help 

best regards

**Comment by vavrecan** [comment]
Not sure what could be the issue, plugin should be signed. Do you have same issue when using install.sh version / keeweb git version?
